### ISSUE TITLE
mvn打包报错

### ISSUE THREAD

**Issue by acm-py** [taosdata/kafka-connect-tdengine#29]
以下是整个打包信息：
环境：ubuntu20.04（虚拟机
java版本：java11
maven版本：3.6.3

[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.taosdata:kafka-connect-tdengine >-----------------
[INFO] Building kafka-connect-tdengine 1.0.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-connect-tdengine ---
[INFO] Deleting /home/software/kafka-connect-tdengine/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-connect-tdengine ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (default) @ kafka-connect-tdengine ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
     [copy] Copying 1 file to /home/software/kafka-connect-tdengine
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-connect-tdengine ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 30 source files to /home/software/kafka-connect-tdengine/target/classes
[WARNING] /home/software/kafka-connect-tdengine/src/main/java/com/taosdata/kafka/connect/config/CharsetValidator.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/software/kafka-connect-tdengine/src/main/java/com/taosdata/kafka/connect/config/CharsetValidator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-connect-tdengine ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/software/kafka-connect-tdengine/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kafka-connect-tdengine ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/software/kafka-connect-tdengine/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ kafka-connect-tdengine ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.taosdata.kafka.connect.source.SourceInsertTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.291 s <<< FAILURE! - in com.taosdata.kafka.connect.source.SourceInsertTest
[ERROR] prepareData  Time elapsed: 0.262 s  <<< ERROR!
java.lang.NoSuchMethodError: commitCallbackHandler
	at com.taosdata.kafka.connect.source.SourceInsertTest.createConnection(SourceInsertTest.java:27)
	at com.taosdata.kafka.connect.source.SourceInsertTest.prepareData(SourceInsertTest.java:21)

[INFO] Running com.taosdata.kafka.connect.source.TimeStampOffsetTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 s - in com.taosdata.kafka.connect.source.TimeStampOffsetTest
[INFO] Running com.taosdata.kafka.connect.config.TimeZoneValidatorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in com.taosdata.kafka.connect.config.TimeZoneValidatorTest
[INFO] Running com.taosdata.kafka.connect.config.SchemalessValidatorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in com.taosdata.kafka.connect.config.SchemalessValidatorTest
[INFO] Running com.taosdata.kafka.connect.TDengineTaskTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.015 s - in com.taosdata.kafka.connect.TDengineTaskTest
[INFO] Running com.taosdata.kafka.connect.sink.TDengineSinkConnectorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.045 s - in com.taosdata.kafka.connect.sink.TDengineSinkConnectorTest
[INFO] Running com.taosdata.kafka.connect.util.VersionUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in com.taosdata.kafka.connect.util.VersionUtilsTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SourceInsertTest.prepareData:21->createConnection:27 » NoSuchMethod commitCall...
[INFO] 
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.159 s
[INFO] Finished at: 2022-12-26T03:58:31-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project kafka-connect-tdengine: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/software/kafka-connect-tdengine/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by huolibo** [comment]
kafka-connect-tdengine master 分支中使用的 jdbc 为 2.0.39 对应 TDengine 2.x 版本。如果需要对 TDengine 3.x 版本需要修改 pom.xml 中 `taos.jdbcdriver.version` 为 3.0.3 版本。

**Comment by acm-py** [comment]
> 

感谢，试了下，可以了。
