### ISSUE TITLE
太多bug，不要使用TDengine-source-connector

### ISSUE THREAD

**Issue by GreatStep** [taosdata/kafka-connect-tdengine#69]
创建kakfa-source-connector后，超级表会被“锁定”；

1）插入新标签的值，无效！—— 直接毁了超级表！
INSERT INTO d1001 USING meters TAGS('houjt', 99) VALUES(now,10.30000,'ttttt','hhhhh');
taos> select * from meters order by ts desc;
           ts            |       current        |           item_tags            |            new_col             |            location            |   groupid   |
==================================================================================================================================================================
 2024-09-23 09:31:02.530 |           10.3000002 | ttttt                          | hhhhh                          | California.SanFrancisco        |           2 |

2）新增字段，kafka-topic 无效！
[{"current":10.8,"ts":1538548685000,"tags":{"groupid":3,"location":"California.LosAngeles"}}]
[{"current":11.5,"ts":1538548686500,"tags":{"groupid":3,"location":"California.LosAngeles"}}]
删除重建 kakfa-source-connector，依然无效！

**Comment by yu285** [comment]
标签值不能通过这个语句修改，先看下文档吧。
标签值只能通过alter 语句修改，这个写入成功只代表数据写入成功。

**Comment by GreatStep** [comment]
看清楚，不是修改已有标签值，是新增一个“不存在“的标签值，都无法添加！我的业务丢失一堆新增的主机ip(新标签值)了

**Comment by GreatStep** [comment]
第二个问题呢？ 
我手动插入几条新记录，td表是有新字段的，但是通过connector 导出到 kafka-topic，看不到有新字段。
销毁connector重建，从头开始消费所有数据，依然没有看到新字段。
